package me.blip.pokeymans;

public enum Position
{
    FRIENDLY_LEFT,FRIENDLY_RIGHT,ENEMY_LEFT,ENEMY_RIGHT,FRIENDLY_BENCH1,FRIENDLY_BENCH2,FRIENDLY_BENCH3,FRIENDLY_BENCH4,ENEMY_BENCH1,ENEMY_BENCH2,ENEMY_BENCH3,ENEMY_BENCH4
}
